### ISSUE TITLE
Crashes during Datagen

### ISSUE THREAD

**Issue by Minemobs** [Minemobs/constructsarmory#1]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 2.0.0-alpha.2+1.18.2
* Tinkers' Construct: 1.18.2-3.5.2.39
* Mantle: 1.18.2-1.9.28
* Forge: 1.18.2-40.1.80
#### Observed Behavior:
Generate data
#### Expected Behavior:
Crashes when a plate is added in ArmorMaterialStatsDataProvider#addMaterialStats
#### Steps to Reproduce:
1. Run ./gradlew runData

[Crash log](https://hastebin.com/ujogiducut.rb)

**Comment by Minemobs** [comment]
Probably due to these lines:
```java
// Tier 3
addMaterialStats(MaterialIds.bronze, 437, 12.0f, 2.0f, 0.05f, 0.055f, 1.05f, 1.0f, 1.1f);
// Tier 3 - Addons
addMaterialStats(MaterialIds.bronze, 453, 11.0f, 2.0f, 0.05f, 0.0575f, 1.1f, 1.0f, 1.05f);
```

**Comment by Minemobs** [comment]
Yeah It is

**Comment by Minemobs** [comment]
Yay, new error
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.80/net.minecraftforge.fml.loading.targets.ForgeDataUserdevLaunchHandler.lambda$launchService$0(ForgeDataUserdevLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: java.lang.IllegalStateException: Cannot fetch a static modifiers before modifiers are registered
	at TRANSFORMER/tconstruct@3.5.2.39/slimeknights.tconstruct.library.modifiers.util.StaticModifier.get(StaticModifier.java:39)
	at TRANSFORMER/constructsarmory@2.0.0-alpha.2+1.18.2/com.illusivesoulworks.constructsarmory.data.ArmorMaterialTraitsDataProvider.addMaterialTraits(ArmorMaterialTraitsDataProvider.java:41)
	at TRANSFORMER/tconstruct@3.5.2.39/slimeknights.tconstruct.library.data.material.AbstractMaterialTraitDataProvider.run(AbstractMaterialTraitDataProvider.java:48)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.DataGenerator.run(DataGenerator.java:53)
	at TRANSFORMER/forge@40.1.80/net.minecraftforge.forge.event.lifecycle.GatherDataEvent$DataGeneratorConfig.lambda$runAll$0(GatherDataEvent.java:98)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.api.LamdbaExceptionUtils.lambda$rethrowConsumer$0(LamdbaExceptionUtils.java:34)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at TRANSFORMER/forge@40.1.80/net.minecraftforge.forge.event.lifecycle.GatherDataEvent$DataGeneratorConfig.runAll(GatherDataEvent.java:94)
	at TRANSFORMER/forge@40.1.80/net.minecraftforge.data.loading.DatagenModLoader.begin(DatagenModLoader.java:45)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.Main.main(Main.java:67)
	... 13 more
```
